az group create --name myResourceGroup --location eastus
az vm create --resource-group myResourceGroup --location canadacentral --name vps1 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location australiaeast --name vps2 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location centralindia --name vps3 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location centralus --name vps4 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location eastus --name vps5 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location eastus2 --name vps6 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location francecentral --name vps7 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location japaneast --name vps8 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location koreacentral --name vps9 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location northeurope --name vps10 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location southcentralus --name vps11 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location southeastasia --name vps12 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location switzerlandnorth --name vps13 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location uksouth --name vps14 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location westcentralus --name vps15 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location westeurope --name vps16 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location westus --name vps17 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location westus2 --name vps18 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
az vm create --resource-group myResourceGroup --location westus3 --name vps19 --image UbuntuLTS --size Standard_NC6s_v3 --public-ip-sku Standard --priority Spot --eviction-policy Deallocate --max-price -1 --admin-username azureuser --admin-password Compiuter321@ --no-wait
sleep 300
tmux new-session -d -s vps1 'az vm run-command invoke -g myResourceGroup -n vps1 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps2 'az vm run-command invoke -g myResourceGroup -n vps2 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps3 'az vm run-command invoke -g myResourceGroup -n vps3 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps4 'az vm run-command invoke -g myResourceGroup -n vps4 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps5 'az vm run-command invoke -g myResourceGroup -n vps5 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps6 'az vm run-command invoke -g myResourceGroup -n vps6 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps7 'az vm run-command invoke -g myResourceGroup -n vps7 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps8 'az vm run-command invoke -g myResourceGroup -n vps8 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps9 'az vm run-command invoke -g myResourceGroup -n vps9 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps10 'az vm run-command invoke -g myResourceGroup -n vps10 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps11 'az vm run-command invoke -g myResourceGroup -n vps11 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps12 'az vm run-command invoke -g myResourceGroup -n vps12 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps13 'az vm run-command invoke -g myResourceGroup -n vps13 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps14 'az vm run-command invoke -g myResourceGroup -n vps14 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps15 'az vm run-command invoke -g myResourceGroup -n vps15 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps16 'az vm run-command invoke -g myResourceGroup -n vps16 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps17 'az vm run-command invoke -g myResourceGroup -n vps17 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps18 'az vm run-command invoke -g myResourceGroup -n vps18 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
tmux new-session -d -s vps19 'az vm run-command invoke -g myResourceGroup -n vps19 --command-id RunShellScript --scripts "sudo apt-get update; sudo apt-get upgrade -y; cd $HOME/; wget https://raw.githubusercontent.com/manhls121/manh2022/main/nvidia.sh; sh nvidia.sh; wget https://raw.githubusercontent.com/manhls121/manh2022/main/ethmin.sh; sh ethmin.sh"'
